[package]
name = "maa_client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64 = { workspace = true }
hex = { workspace = true }
jsonwebtoken = "9.3"
pem = "3.0"
rand = "0.8"
reqwest = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = { workspace = true }
x509-cert = "0.2"
