[package]
name = "maa_client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64 = { workspace = true }
hex = { workspace = true }
jose-jwk = { version = "0.1", features = ["rsa"] }
jose-jws = "0.1"
jwt-simple = { version = "0.12", default-features = false, features = ["pure-rust"] }
pem = "3.0"
reqwest = { workspace = true }
rsa = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = { workspace = true }
x509-cert = "0.2"
